# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo
# Copied from xarray's example
branches:
  except:
    - gh-pages

environment:

  matrix:
    - PYTHON: "C:\\Python36-conda64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_ENV: "py36-windows"

install:
  # Install miniconda Python
  - "powershell ./ci/install_python.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # install yodapy and dependencies
  - "conda update conda --yes"
  - "conda config --set show_channel_urls true"
  - "conda config --add channels conda-forge --force"
  - "conda create --yes -n TEST python=%PYTHON_VERSION% --file requirements.txt --file requirements-dev.txt"
  - "activate TEST"
  - "conda list"
  - "python setup.py install"

build: false

test_script:
- "pytest -vv tests"